@startuml

'hide footbox
skinparam shadowing false
actor ユーザ

participant departmentAddComplete.jsp
participant error.jsp

ユーザ -> MenuController : doPost()
activate DepartmentAddCompleteServlet

DepartmentAddCompleteServlet -> DepartmentService : addDepartment()
activate DepartmentService

DepartmentService -> DepartmentDAO : addDepartment()
activate DepartmentDAO

database DB
DepartmentDAO -> DB : SQL:INSERT

DB --> DepartmentDAO : int result

DepartmentDAO --> DepartmentService : int result
deactivate DepartmentDAO

DepartmentService --> DepartmentAddCompleteServlet : int result
deactivate DepartmentService

DepartmentAddCompleteServlet -> DepartmentAddCompleteServlet : セッション削除

DepartmentAddCompleteServlet -> DepartmentAddCompleteServlet : リクエストに部署をセット

alt password ok
	DepartmentAddCompleteServlet --> departmentAddComplete.jsp : フォワード
	'deactivate DepartmentAddCompleteServlet
	'activate departmentAddComplete.jsp
else password ng
	DepartmentAddCompleteServlet --> error.jsp : フォワード
	deactivate DepartmentAddCompleteServlet
	'activate departmentAddComplete.jsp
end

departmentAddComplete.jsp --> ユーザ : 部署登録完了画面
deactivate departmentAddComplete.jsp

@enduml