@startuml
!include ./config.txt
title UC004: 商品購入 シーケンス図
actor "ユーザ" as user
participant "PurchaseController" as ctrl
' participant "PurchaseForm" as form
participant "ProductCart" as cart
participant "ProductService" as svc
participant "ProductRepository" as repo
database DB as db

' 入力画面
user -> ctrl ++ : GET\n/product/{productId}
note right: 商品情報取得
ctrl -> svc ++ : findById(productId)
svc -> repo ++ : findById(productId)
repo -> db ++ : SQL SELECT
db --> repo -- : Product
repo --> svc -- : Product
svc --> ctrl -- : Product
ctrl -> ctrl : Model追加(Product)
ctrl -> user -- : 商品詳細画面

' 商品購入
user -> user : 個数入力
user -> ctrl ++ : POST\n/cart/add
note right: カートに入れた商品の在庫数を\n取得してプルダウン項目を生成
ctrl -> cart ++ : add(Product)
cart -> cart : カートに商品追加
ctrl <-- cart -- : void
ctrl --> user-- : リダイレクト
user -> ctrl ++ : GET\n/cart/list
ctrl -> svc ++ : selectByProductList\n(List<Product>)
svc -> repo ++ : selectByProductList\n(List<Product>)
repo -> db ++ : SQL SELECT
repo <-- db -- : List<Product>
svc <-- repo -- : List<Product> 
ctrl <-- svc -- : List<Product>
ctrl -> ctrl : 個数のプルダウン生成
ctrl -> user -- : カート画面

@enduml