@startuml
!include ./config.txt
title UC009: 担当者アカウント登録機能 シーケンス図
actor ユーザ as user
activate user
participant "EmployeeAccountAdd\nController" as controller
participant "Employee\nService" as svc1
participant "Employee\nRepository" as repo1
participant "EmployeeAccount\nService" as svc2
participant "EmployeeAccount\nRepository" as repo2
database DB as db

' 入力画面
user -> controller ++ : GET\n/admin/emp-add\nform()
controller -> controller : setUpForm()
controller -> controller : bind()
controller -> svc1 ++ : findAll()
svc1 -> repo1 ++ : findAll()
repo1 -> db ++ : SELECT文
repo1 <-- db -- : List<Employee>
svc1 <- repo1 -- : List<Employee>
controller <-- svc1 --  : List<Employee>
controller -> user -- : 入力画面

' 確認画面
user -> user : 商品情報入力
user -> controller ++ : POST\n/admin/emp-add/confirm\nconfirm()
controller -> controller : バリデート
controller --> user -- : 確認画面

' 完了画面
user -> user : 入力内容確認
user -> controller ++ : POST\n/admin/emp-add/execute\nexecute()
controller -> controller : セッション確認
' note right: フォームデータが\n空ならシステムエラー
controller -> controller : フォームから\nエンティティに変換
controller -> svc2 ++ : insert\n(EmpployeeAccount)
svc2 -> repo2 ++ : insert\n(EmpployeeAccount)
repo2 -> db ++ : INSERT文
repo2 <-- db -- : void
svc2 <-- repo2 -- : void
svc2 -> controller -- : void
user <-- controller-- : リダイレクト
user -> controller++ : GET\n/admin/emp-add/complete
controller -> controller : セッション破棄
controller -> controller : Model追加
controller -> user-- : 完了画面
deactivate user
@enduml