@startuml

title UC017: 社員アカウントログアウト機能 シーケンス図
skinparam shadowing false

actor "ユーザ" as user
participant "LoginController" as ctrl
participant "SpringSecurity本体" as sec
activate user

user -> sec ++ : ログアウト
sec -> sec : セッション破棄
sec -> user -- : ログイン画面にリダイレクト
user -> ctrl ++ : login()
ctrl --> user -- : ログイン画面

@enduml