@startuml
!include ./config.txt
title UC014: カテゴリ登録機能 シーケンス図

actor "ユーザ" as user
activate user
participant "ProductCategoryAddController" as ctrl
participant "ProductCategoryService" as svc
participant "ProductCategoryRepository" as repo
database DB as db

' 入力画面
user -> ctrl ++ : GET\n/admin/product-category-add/form\nform()
ctrl -> ctrl : setUpForm()
note right: セッション生成
ctrl -> ctrl : bind()
ctrl -> user -- : 入力画面

' 確認画面
user -> user : 商品情報入力
user -> ctrl ++ : POST\n/admin/product-category-add/confirm\nconfirm()
ctrl -> ctrl : バリデート
ctrl --> user -- : 確認画面

' 完了画面
user -> user : 入力内容確認
user -> ctrl ++ : POST\n/admin/product-category-add/execute\nexecute()
ctrl -> ctrl : セッション確認
note right: セッションが空なら\nシステムエラー
ctrl -> ctrl : フォームを\nエンティティに変換
ctrl -> svc ++ : insert\n(ProductCategory)
svc -> repo ++ : insert\n(ProductCategory)
repo -> db ++ : SQL INSERT
db --> repo -- : void
repo --> svc -- : void
svc -> ctrl -- : void
user <-- ctrl -- : リダイレクト
user -> ctrl ++ : GET\n/admin/product-category-add/complete\ncomplete()
ctrl -> ctrl : セッション破棄
ctrl -> ctrl : Modelに追加（商品名）
ctrl -> user -- : 完了画面

@enduml