@startuml
!include ./config.txt
title UC013: 商品削除機能 シーケンス図

actor ユーザ
activate ユーザ

ユーザ -> ProductDeleteController : GET\n/admin/product-delete/{productId}\nconfirm(productId)
activate ProductDeleteController

ProductDeleteController -> ProductService : findById(productId)
activate ProductService

ProductService -> ProductRepository : findById(productId)
activate ProductRepository

database DB

ProductRepository -> DB : SELECT文
activate DB

DB --> ProductRepository : Product
deactivate DB

ProductRepository --> ProductService : Product
deactivate ProductRepository

ProductService --> ProductDeleteController
deactivate ProductService

ProductDeleteController -> ProductDeleteController : Modelに追加
note right: セッションには格納しない

ProductDeleteController --> ユーザ : 確認画面
deactivate ProductDeleteController

ユーザ -> ProductDeleteController : POST\n/admin/product-delete/execute\nexecute()
activate ProductDeleteController

ProductDeleteController -> ProductService : delete(Integer no)
activate ProductService

ProductService -> ProductRepository : delete(Integer no)
activate ProductRepository

note right: 物理でなく論理削除
ProductRepository -> DB : UPDATE文
activate DB

DB --> ProductRepository : void
deactivate DB

ProductRepository --> ProductService : void
deactivate ProductRepository

ProductService --> ProductDeleteController : void
deactivate ProductService

ProductDeleteController -> ProductDeleteController : Modelに追加（商品名）

ProductDeleteController --> ユーザ : リダイレクト
deactivate ProductDeleteController
note right: PRGパターンにより二重投稿防止

ユーザ -> ProductDeleteController : GET\nadmin/product-delete/complete\ncomplete()
activate ProductDeleteController

ProductDeleteController --> ユーザ : 完了画面
deactivate ProductDeleteController

@enduml