@startuml
!include ./config.txt
title UC017: 社員アカウントログアウト機能 シーケンス図

actor "ユーザ" as user
participant "LoginController" as ctrl
participant "SpringSecurity本体" as sec
activate user

user -> sec ++ : POST\n/admin/logout
sec -> sec : セッション破棄
sec -> user -- : ログイン画面にリダイレクト
user -> ctrl ++ : GET\n/admin/login\nlogin()
ctrl --> user -- : ログイン画面

@enduml