@startuml

title UC017: 社員アカウントログイン機能 シーケンス図
skinparam shadowing false
actor "user" as user
activate user
participant "Login\nController" as ctrl1
participant "Menu\nController" as ctrl2
participant "SpringSecurity" as sec
participant "EmployeeAccount\nUserDetailsService" as svc
participant "EmployeeAccount\nRepository" as repo
participant "EmployeeAccount\nUserDetails" as ud
database DB as db

user -> ctrl1 ++ : form()
ctrl1 -> user -- : ログイン画面
user -> sec ++ : 認証
sec -> svc ++ : loadUserByUsername\n(userName)
svc -> repo ++ : findByUserName\n(userName)
repo -> db ++ : SELECT文
db --> repo -- : EmployeeAccount
repo --> svc -- : EmployeeAccount
svc -> ud ++ : new
ud --> svc -- : EmployeeAccount\nUserDetails
svc --> sec -- : EmployeeAccount\nUserDetails
sec -> sec : セッションに格納
sec --> user -- : リダイレクト
user -> ctrl2 ++ : menu()
ctrl2 --> user -- : メニュー画面

deactivate user

@enduml