@startuml

title UC012: 商品修正機能 シーケンス図
skinparam shadowing false
'hide footbox

actor ユーザ

activate ユーザ

ユーザ -> ProductUpdateController : form()
activate ProductUpdateController

ProductUpdateController -> ProductUpdateController : setUpForm()
'note right: セッション生成

ProductUpdateController -> ProductUpdateController : bind()

ProductUpdateController -> ProductCategoryService : findAll()
activate ProductCategoryService

ProductCategoryService -> ProductCategoryRepository : findAll()
activate ProductCategoryRepository

participant ProductService

participant ProductRepository

participant ProductStockRepository

database DB

ProductCategoryRepository -> DB : SELECT文
activate DB

DB --> ProductCategoryRepository : List<ProductCategory>
deactivate DB

ProductCategoryRepository -> ProductCategoryService : List<ProductCategory>
deactivate ProductCategoryRepository

ProductCategoryService --> ProductUpdateController : List<ProductCategory>
deactivate ProductCategoryService

ProductUpdateController -> ProductService : findById(int)
activate ProductService

ProductService -> ProductRepository : findById(int)
activate ProductRepository

ProductRepository -> DB : SELECT文
activate DB

DB --> ProductRepository : Product
deactivate DB

ProductRepository --> ProductService : Product
deactivate ProductRepository

ProductService --> ProductUpdateController : Product
deactivate ProductService

ProductUpdateController -> ProductUpdateController : エンティティから\nフォームに変換
ProductUpdateController -> ProductUpdateController : Model追加\n（フォーム）
ProductUpdateController -> ProductUpdateController : Model追加\n（商品カテゴリリスト）
ProductUpdateController -> ProductUpdateController : Model追加\n（商品）

ProductUpdateController -> ユーザ : 入力画面
deactivate ProductUpdateController

ユーザ -> ユーザ : 商品情報修正

ユーザ -> ProductUpdateController : confirm()
activate ProductUpdateController

ProductUpdateController -> ProductUpdateController : バリデート

alt バリデート結果 エラーあり
    ProductUpdateController -> ユーザ : 入力画面
else バリデート結果 エラーなし
    alt 画像修正あり
        ProductUpdateController -> ProductUpdateController : セッション追加\n（新画像Base64）
        ProductUpdateController -> ProductUpdateController : セッション追加\n（新画像バイトデータ）
    else 画像修正なし
        ProductUpdateController -> ProductUpdateController : Model追加\n（"/img/"+元画像ファイル名）
    end
    ProductUpdateController -> ユーザ : 確認画面
    deactivate ProductUpdateController

    ユーザ -> ユーザ : 入力内容確認

    ユーザ -> ProductUpdateController : complete()
    activate ProductUpdateController

    ProductUpdateController -> ProductUpdateController : セッション確認
    note right: フォームが空の場合はシステムエラー

    ProductUpdateController -> ProductUpdateController : フォームから\nエンティティに変換

    ProductUpdateController -> ProductService : update(Product product)
    activate ProductService

    ProductService -> ProductRepository : update(Product product)
    activate ProductRepository

    ProductRepository -> DB : UPDATE文

    activate DB

    DB --> ProductRepository : void

    deactivate DB

    ProductRepository --> ProductService : void
    deactivate ProductRepository

    ProductService -> ProductStockRepository : update(ProductStock)
    activate ProductStockRepository

    ProductStockRepository -> DB : UPDATE文
    activate DB

    DB --> ProductStockRepository : void

    deactivate DB

    ProductStockRepository --> ProductService : void
    deactivate ProductStockRepository

    ProductService --> ProductUpdateController : void
    deactivate ProductService

    ProductUpdateController -> ProductUpdateController : セッション破棄

    ProductUpdateController -> ProductUpdateController : Model追加（商品名）

    ProductUpdateController -> ユーザ : 完了画面
    deactivate ProductUpdateController
end

@enduml