@startuml
!include ./config.txt
title configパッケージ
package config{
    class AppConfig <<@Configuration>>{
        addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) : void
    }
}

@enduml