@startuml

title configパッケージ
left to right direction

package config{
    class AppConfig <<@Configuration>>{
        addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) : void
    }
}

@enduml