@startuml
!include ./config.txt
title securityパッケージ
package security{
    class EmployeeAccountUserDetails{
        - account : EmployeeAccount
        - authorites : Collection<GrantedAuthority>
        + getAuthorities() : Collection<? extends GrantedAuthority>
        + getPassword() : String
        + getUsername() : String
        + isAccountNonExpired() : boolean
        + isAccountNonLocked() : boolean
        + isCredentialsNonExpired() : boolean
        + isEnabled() : boolean
    }
    class EmployeeAccountUserDetailsService{
        - employeeAccountRepository : EmployeeAccountRepository
        + loadUserByUsername(String username) : UserDetails
'        + getAuthority(EmployeeAccount account) : Collection<GrantedAuthority>
    }
    class EmployeeAccountSecurityConfig{
        - accountDetailsService : EmployeeAccountUserDetailsService
        + passwordEncoder() : PasswordEncoder
        + configureAuthenticationManager(AuthenticationManagerBuilder auth) : void
        + configure(WebSecurity web) : void
        + configure(HttpSecurity http) : void
    }
    class CustomerAccountUserDetails{
        - account : Customer
        - authorites : Collection<GrantedAuthority>
        + getAuthorities() : Collection<? extends GrantedAuthority>
        + getPassword() : String
        + getUsername() : String
        + isAccountNonExpired() : boolean
        + isAccountNonLocked() : boolean
        + isCredentialsNonExpired() : boolean
        + isEnabled() : boolean
    }
    class CustomerUserDetailsService{
        - customerRepository : CustomerRepository
        + loadUserByUsername(String username) : UserDetails
'        + getAuthority(EmployeeAccount account) : Collection<GrantedAuthority>
    }
    class CustomerSecurityConfig{
        - customerDetailsService : CustomerUserDetailsService
        + passwordEncoder() : PasswordEncoder
        + configureAuthenticationManager(AuthenticationManagerBuilder auth) : void
        + configure(WebSecurity web) : void
        + configure(HttpSecurity http) : void
    }
}
EmployeeAccountSecurityConfig --> EmployeeAccountUserDetailsService :use
CustomerSecurityConfig --> CustomerUserDetailsService :use

@enduml