@startuml

skinparam shadowing false
hide empty methods
hide empty fields
left to right direction

package security{
    class EmployeeAccountUserDetails{
        - Account account
        - Collection<GrantedAuthority> authorites
        + Collection<? extends GrantedAuthority> getAuthorities()
        + String getPassword()
        + String getUsername()
        + boolean isAccountNonExpired()
        + boolean isAccountNonLocked()
        + boolean isCredentialsNonExpired()
        + boolean isEnabled()
    }
    class EmployeeAccountUserDetailsService{
        - EmployeeAccountRepository employeeAccountRepository
        + UserDetails loadUserByUsername(String username)
        + Collection<GrantedAuthority> getAuthority(EmployeeAccount account)
    }
    class EmployeeAccountSecurityConfig{
        - EmployeeAccountUserDetailsService accountDetailsService
        + PasswordEncoder passwordEncoder()
        + void configureAuthenticationManager(AuthenticationManagerBuilder auth)
        + void configure(WebSecurity web)
        + void configure(HttpSecurity http)
    }
}
EmployeeAccountSecurityConfig --> EmployeeAccountUserDetailsService :use
@enduml