@startuml

title entityパッケージ
left to right direction

package entity{
    class Product<<@Data>>{
        - id:Integer 
        - name:String 
        - price:Integer
        - imageUrl:String
        - productCategory:ProductCategory 
        - deleteFlag:Integer
    }
    class ProductCategory<<@Data>>{
        - id:Integer
        - name:String
    }
    class ProductStock<<@Data>>{
        - id:Integer
        - quantity:Integer
        - productId:Integer
    }
    class EmployeeAccount<<@Data>>{
        - id:Integer
        - name:String
        - password:String
        - employeeId:Integer
    }
    class Employee<<@Data>>{
        - id:Integer
        - name:String
        - nameKana:String
        - departmentId:Integer
    }
    class Customer<<@Data>>{
        - id:Integer
        - name:String
        - nameKana:String
        - address1:String
        - address2:String
        - phoneNumber:String
        - mailAddress:String
        - username:String
        - password:String
        - Date registerDate
    }
    class Order<<@Data>>{
        - id:Integer
        - customerId:Integer
        - orderStatusId:Integer
        - orderDate:Date
        - amountTotal:Integer
    }
    class OrderStatus<<@Data>>{
        - id:Integer
        - name:String
    }
    class OrderDetail<<@Data>>{
        - id:Integer
        - orderId:Integer
        - productId:Integer
        - customerId:Integer
        - count:Integer
    }
}
@enduml