@startuml

title controllerパッケージ
left to right direction

package controller{
    class GlobalExceptionAspect{
        ModelAndView exceptionCaught()
    }
    package backend{
        class MenuController{
            + menu() : String
        }
        class LoginController{
            - service : EmployeeAccountService
            + setUpForm() : LoginForm
            + form() : String
        }
        class ProductSearchController{
            - productService : ProductService
            - productCategoryService : ProductCategoryService
            + list(Model model) : String
            + search(Model model) : String
        }
        class ProductAddController{
            - validator : ProductFormValidator
            - productService : ProductService
            - productCategoryService : ProductCategoryService
            + setUpForm() : ProductForm
            + bind(WebDataBinder binder) : void
            + form(Model model) : String
            + confirm(ProductForm form, BindingResult result, Model model) : String
            + execute(ProductForm form) : String
            + complete(ProductForm form, SessionStatus session) : String
            + cancel() : String
        }
        class ProductUpdateController{
            - validator : ProductFormValidator
            - productService : ProductService
            - productCategoryService : ProductCategoryService
            + setUpForm() : ProductForm
            + bind(WebDataBinder binder) : void
            + form(Model model) : String
            + confirm(ProductForm form, BindingResult result, Model model) : String
            + execute(ProductForm form) : String
            + complete(ProductForm form, SessionStatus session) : String
            + cancel(SessionStatus session) : String
        }
        class ProductDeleteController{
            - productService : ProductService
            - productCategoryService : ProductCategoryService
            + confirm(ProductForm form, BindingResult result, Model model) : String
            + complete(ProductForm form, SessionStatus session) : String
            + execute(ProductForm form) : String
            + cancel(SessionStatus session) : String
        }
        class ProductCategoryAddController{
            - ProductCategoryService productCategoryService
            + String form()
            + String confirm(ProductCategoryForm form, BindingResult result)
            + String complete(ProductCategoryForm form, SessionStatus session)
            + String cancel(SessionStatus session)
        }
        class EmployeeAccountAddController{
            - employeeAccountService : EmployeeAccountService
            - validator : EmployeeAccountFormValidator
            + setUpForm() : EmployeeAccountForm
            + bind(WebDataBinder binder) : void
            + form(Model model) : String
            + confirm(EmployeeAccountForm form, BindingResult result, Model model) : String
            + execute(EmployeeAccountForm form) : String
            + complete(EmployeeAccountForm form) : String
            + cancel(SessionStatus session) : String
        }
    }
}

@enduml