@startuml
!include ./config.txt
title repositoryパッケージ
package repository{
    interface ProductRepository{
        + {abstract} findAll() : List<Product>
        + {abstract} findByCategoryId(int productCategoryId) : List<Product>
        + {abstract} findById(Integer id) : Product
        + {abstract} insert(Product product) : void
        + {abstract} update(Product product) : void
        + {abstract} delete(Integer id) : void
    }
    interface ProductCategoryRepository{
        + {abstract} findAll() : List<ProductCategory>
        + {abstract} findById(Integer id) : ProductCategory
        + {abstract} insert(ProductCategory productCategory) : void
    }
    interface ProductStockRepository{
        + {abstract} insert(ProductStock productStock) : void
        + {abstract} update(ProductStock productStock) : void
    }
    interface EmployeeAccountRepository{
        + {abstract} findAll() : List<EmployeeAccount>
        + {abstract} findById(Integer id) : EmployeeAccount
        + {abstract} findByUsername(String Username) : EmployeeAccount
        + {abstract} isExist(String userName): boolean
        + {abstract} insert(EmployeeAccount employeeAccount) : void
    }
    interface EmployeeRepository{
        + {abstract} findAll() : List<Employee>
    }
    interface CustomerRepository{
        + {abstract} insert(Customer customer) : void
    }
    interface OrderRepository{
        + {abstract} insert(Order order) : void
    }
    interface OrderDetailRepository{
        + {abstract} insert(OrderDetail orderDetail) : void
    }
    interface OrderStatusRepository{
        + {abstract} insert(OrderStatus orderStatus) : void
        + {abstract} update(OrderStatus orderStatus) : void
    }
}
@enduml