@startuml

title formパッケージ
left to right direction

package form {
    class "LoginForm" as LoginForm{
        - name : String
        - password : String
    }
    class "ProductForm" as ProductForm{
        - name : String
        - price : Integer
        - stock : Integer
        - productCategoryId : Integer
        - image : MultipartFile
    }
    class "ProductFormValidator" as ProductFormValidator{
        + supports(Class<?> clazz) : boolean 
        + validate(Object target, Errors errors) : void 
    }
    class "ProductCategoryForm" as ProductCategoryForm{
        - name : String
    }
    class "ProductCategoryFormValidator" as ProductCategoryFormValidator{
        + supports(Class<?> clazz) : boolean 
        + validate(Object target, Errors errors) : void
    }
    class "EmployeeAccountForm" as EmployeeAccountForm{
        - employeeId : Integer
        - userName : String
        - password : String
    }
    class "EmployeeAccountFormValidator" as EmployeeAccountFormValidator{
        + supports(Class<?> clazz) : boolean 
        + validate(Object target, Errors errors) : void 
    }
    class "CustomerResigterForm" as CustomerResigterForm{
        - name : String
        - nameKana : String
        - address1 : String
        - address2 : String
        - phoneNumber : String
        - mailAddress : String
        - username : String
        - password : String
    }
    class "CustomerLoginForm" as CustomerLoginForm{
        - name : String
        - password : String
    }
    class "OrderForm" as OrderForm{
    }
}

@enduml