@startuml

skinparam shadowing false
left to right direction
'skinparam monochrome true

frame "メニュー\n（ログイン前）" as p001_before <<P001>>
frame "メニュー\n（ログイン後）" as p001_after <<P001>>
frame "担当者ログイン" as p002 <<P002>>
frame "アカウント\n登録(入力)" as p003 <<P003>>
frame "アカウント\n登録(確認)" as p004 <<P004>>
frame "アカウント\n登録(完了)" as p005 <<P005>>
frame "商品検索\n" as p006 <<P006>>
frame "商品削除\n(確認)" as p007 <<P007>>
frame "商品削除\n(完了)" as p008 <<P008>>
frame "商品修正\n(入力)" as p009 <<P009>>
frame "商品修正\n(確認)" as p010 <<P010>>
frame "商品修正\n(完了)" as p011 <<P011>>
frame "商品登録\n(入力)" as p012 <<P012>>
frame "商品登録\n(確認)" as p013 <<P013>>
frame "商品登録\n(完了)" as p014 <<P014>>
frame "購入履歴検索" as p015 <<P015>>
frame "配送手続き\n(入力)" as p016 <<P016>>
frame "配送手続き\n(確認)" as p017 <<P017>>
frame "配送手続き\n(完了)" as p018 <<P018>>
frame "商品カテゴリ\n登録(入力)" as p019 <<P019>>
frame "商品カテゴリ\n登録(確認)" as p020 <<P020>>
frame "商品カテゴリ\n登録(完了)" as p021 <<P021>>

interface start

start -ri-> p001_before
p001_before -ri-> p002

p002 --> p002 : ログイン失敗
p002 -ri-> p001_after : ログイン成功
p001_after -le-> p001_before : ログアウト

p001_after --> p015 : 購入履歴
p015 --> p016

p001_after --> p006 : 商品情報メンテナンス
p001_after --> p003 : アカウント登録
p001_after --> p019 : 商品カテゴリ登録

p019 --> p019 : 入力エラー
p019 --> p020 : 確認
p019 <-- p020 : 戻る
p020 --> p021 : 登録
p021 --> p019 : 入力に戻る
p021 --> p001_after : 業務終了

p003 --> p003 : 入力エラー
p003 --> p004 : 確認
p003 <-- p004 : 戻る
p004 --> p005 : 登録
p005 --> p003 : 入力に戻る
p005 --> p001_after : 業務終了

p006 --> p012 : 商品登録
p012 --> p012 : 入力エラー
p012 --> p013 : 確認
p012 <-- p013 : 戻る
p013 --> p014 : 登録
p014 --> p006 : 商品検索に戻る
p014 --> p012 : 入力に戻る
p014 --> p001_after : 業務終了

p006 --> p009 : 商品修正
p009 --> p009 : 入力エラー
p009 --> p010 : 確認
p009 <-- p010 : 戻る
p010 --> p011 : 修正
p011 --> p006 : 商品検索に戻る
p011 --> p001_after : 業務終了

p006 --> p007 : 商品削除
p006 <-- p007 : キャンセル
p007 --> p008 : 削除
p008 --> p006 : 商品検索に戻る
p008 --> p001_after : 業務終了

p001_after --> p016 : 配送手続き
p016 --> p016 : 入力エラー
p016 --> p017 : 確認
p016 <-- p017 : 戻る
p017 --> p018 : 登録
p018 --> p016 : 入力に戻る
p018 --> p001_after : 業務終了
@enduml